package assemble

import (
	"fmt"
	"strings"

	"kbase/internal/distill"
	"kbase/internal/treeplan"
)

// §4.2 and §4.3's grammar. Every string a rendered index or entry-point
// carries comes from the tree plan or from a constant in this file, which is
// what makes §0.3's drift class unrepresentable rather than checked: there is
// no second place a title, a scope line or a path is computed (I-1).
//
// The three elements shared with the leaf kind — the up-link, the relative
// path and the provenance footer — are internal/distill's, called from here
// [MAD1: F-9].
const (
	// derivationsHeading opens an index's down-link list. It is mandatory on
	// every index (§9 check 9): an index without one is a routing node that
	// routes nowhere.
	derivationsHeading = "## Derivations and Detail"

	// domainsHeading is the entry-point's counterpart of the same list.
	domainsHeading = "## Domains"

	// usingHeading and annexHeading are the entry-point's two mandatory
	// trailing blocks [MAD1: F-5]. The annex one is present iff the tree plan
	// declares annexes.
	usingHeading = "## Using this knowledge base"
	annexHeading = "## Annex lookup"

	// contractText is SPEC §3's statement, verbatim, and it is a constant
	// because §4.3's entry-point and §8.1's AGENTS.md fixture both render it —
	// one string, two render sites, no second place to drift.
	contractText = "**Summaries route; leaves answer.** An index page tells you where to go; " +
		"a page at the bottom of the tree is where the answer is. Answer from leaf text, " +
		"never from an index summary — the summaries are navigation, and they are not the source."

	// agentsPointer names the shipped `.agents/` directory and what is in it.
	// Same rule as contractText: one string, rendered by the entry-point and
	// by AGENTS.md.
	agentsPointer = "The `.agents/` directory beside this file holds the definitions that ship " +
		"with every kbase knowledge base: a docent for navigating it, a maintainer for " +
		"extending it, an adaptation note, and the routing-eval question set."

	// generatedNotice marks a class-B fixture as machine-written. A file a
	// human might reasonably edit has to say that kbase rewrote it, because
	// kbase will.
	generatedNotice = "<!-- generated by kbase; edits are overwritten on the next build -->"
)

// Renderer renders the node kinds stage 8 owns — index and entry-point — and
// the class-B fixtures that ship beside them.
//
// Leaves are not here: stage 5 rendered them whole and stage 8 copies them
// byte-for-byte, because rebasing happened once and this stage does not touch
// leaf bytes [MAD1: F-9].
type Renderer struct {
	plan     treeplan.TreePlan
	prov     distill.Provenance
	children map[string][]treeplan.Node
	titles   map[string]string
}

// NewRenderer returns a renderer over one job's tree plan.
func NewRenderer(plan treeplan.TreePlan, prov distill.Provenance) (*Renderer, error) {
	if plan.Schema != treeplan.SchemaVersion {
		return nil, fmt.Errorf("assemble: tree plan declares schema %q, this build reads %q",
			plan.Schema, treeplan.SchemaVersion)
	}
	if err := prov.Validate(); err != nil {
		return nil, err
	}
	r := &Renderer{
		plan:     plan,
		prov:     prov,
		children: map[string][]treeplan.Node{},
		titles:   make(map[string]string, len(plan.Nodes)),
	}
	for _, n := range plan.Nodes {
		r.titles[n.Path] = n.Title
		if n.Parent != "" {
			r.children[n.Parent] = append(r.children[n.Parent], n)
		}
	}
	return r, nil
}

// Node renders one index or entry-point node.
func (r *Renderer) Node(n treeplan.Node) ([]byte, error) {
	switch n.Kind {
	case treeplan.KindEntryPoint:
		return r.entryPoint(n)
	case treeplan.KindIndex:
		return r.index(n)
	default:
		return nil, fmt.Errorf("assemble: %s is a %s; stage 8 copies pages, it does not render them", n.Path, n.Kind)
	}
}

// index renders §4.2's grammar.
//
// The framing and conclusions blocks are absent, and their absence is legal
// (O-1): with no summary artifact for this node, a mechanically renderable
// index is up-link, H1 and the down-link list. That is what makes the whole
// tree assemblable before stage 6 exists — and it is the same code path stage 6
// will fill in, not a temporary one.
func (r *Renderer) index(n treeplan.Node) ([]byte, error) {
	kids := r.children[n.Path]
	if len(kids) == 0 {
		return nil, fmt.Errorf("assemble: %s is a section with no entries under it", n.Path)
	}
	parent, ok := r.titles[n.Parent]
	if !ok {
		return nil, fmt.Errorf("assemble: %s names parent %q, which the tree plan does not hold", n.Path, n.Parent)
	}
	var b strings.Builder
	b.WriteString(distill.UpLink(parent, distill.RelPath(n.Path, n.Parent)))
	b.WriteString("\n\n# ")
	b.WriteString(n.Title)
	b.WriteString("\n\n")
	b.WriteString(derivationsHeading)
	b.WriteString("\n\n")
	r.downLinks(&b, n, kids)
	b.WriteString("\n")
	b.WriteString(r.prov.Footer())
	b.WriteString("\n")
	return []byte(b.String()), nil
}

// entryPoint renders §4.3's grammar, including the three blocks [MAD1: F-5]
// made template elements: the contract text, the `.agents/` pointer, and the
// annex lookup when there is one.
func (r *Renderer) entryPoint(n treeplan.Node) ([]byte, error) {
	kids := r.children[n.Path]
	if len(kids) == 0 {
		return nil, fmt.Errorf("assemble: the entry-point has no domains")
	}
	var b strings.Builder
	b.WriteString("# ")
	b.WriteString(n.Title)
	b.WriteString("\n\n")
	b.WriteString(domainsHeading)
	b.WriteString("\n\n")
	r.downLinks(&b, n, kids)
	b.WriteString("\n")
	b.WriteString(usingHeading)
	b.WriteString("\n\n")
	b.WriteString(contractText)
	b.WriteString("\n\n")
	b.WriteString(agentsPointer)
	b.WriteString("\n")
	if len(r.plan.Annexes) > 0 {
		b.WriteString("\n")
		b.WriteString(annexHeading)
		b.WriteString("\n\n")
		for _, a := range r.plan.Annexes {
			fmt.Fprintf(&b, "- `%s` — %s\n", a.Prefix, a.Convention)
		}
	}
	b.WriteString("\n")
	b.WriteString(r.prov.Footer())
	b.WriteString("\n")
	return []byte(b.String()), nil
}

// downLinks writes the children list: title and scope straight from the tree
// plan, paths computed (§2.2).
func (r *Renderer) downLinks(b *strings.Builder, parent treeplan.Node, kids []treeplan.Node) {
	for _, c := range kids {
		fmt.Fprintf(b, "- [%s](%s) — %s\n", c.Title, distill.RelPath(parent.Path, c.Path), c.Scope)
	}
}

// Children is one node's children in tree-plan order — the same order the
// down-link list renders in, which is what §9 check 5 compares against.
func (r *Renderer) Children(path string) []treeplan.Node { return r.children[path] }
