package assemble

import (
	"fmt"
	"strings"

	"kbase/internal/distill"
	"kbase/internal/summarize"
	"kbase/internal/treeplan"
)

// §4.2 and §4.3's grammar. Every string a rendered index or entry-point
// carries comes from the tree plan or from a constant in this file, which is
// what makes §0.3's drift class unrepresentable rather than checked: there is
// no second place a title, a scope line or a path is computed (I-1).
//
// The four elements shared with the leaf kind — the frontmatter block, the
// up-link, the relative path and the provenance footer — are
// internal/distill's, called from here [MAD1: F-9].
const (
	// derivationsHeading opens an index's down-link list. It is mandatory on
	// every index (§9 check 9): an index without one is a routing node that
	// routes nowhere.
	derivationsHeading = "## Derivations and Detail"

	// domainsHeading is the entry-point's counterpart of the same list.
	domainsHeading = "## Domains"

	// usingHeading and annexHeading are the entry-point's two mandatory
	// trailing blocks [MAD1: F-5]. The annex one is present iff the tree plan
	// declares annexes.
	usingHeading = "## Using this knowledge base"
	annexHeading = "## Annex lookup"

	// noCrawlInvariant leads the contract and is also a bullet of the CLAUDE.md
	// fixture, so it is its own constant: the duplication between those two is
	// deliberate (a session's read-AGENTS.md hop is probabilistic), and a
	// duplicated STRING would drift.
	//
	// It carries no reason. A directive with a rationale attached is a
	// conditional to a small model — it evaluates whether the reason applies
	// and then decides — and an invariant that can be evaluated away is not one.
	noCrawlInvariant = "INVARIANT: Answers come exclusively from the text of one or more leaves. " +
		"Intermediate nodes are for navigation only."

	// contractText is SPEC §3's statement, verbatim, and it is a constant
	// because §4.3's entry-point and §8.1's AGENTS.md fixture both render it —
	// one string, two render sites, no second place to drift.
	contractText = noCrawlInvariant + "\n\n" +
		"**Summaries route; leaves answer.** An index page tells you where to go; " +
		"a page at the bottom of the tree is where the answer is. Answer from leaf text, " +
		"never from an index summary — the summaries are navigation, and they are not the source."

	// agentsPointer names the shipped `.agents/` directory and what is in it.
	// Same rule as contractText: one string, rendered by the entry-point and
	// by AGENTS.md.
	agentsPointer = "The `.agents/` directory beside this file holds the definitions that ship " +
		"with every kbase knowledge base: a docent for navigating it, a maintainer for " +
		"extending it, an adaptation note, and the routing-eval question set."

	// generatedNotice marks a class-B fixture as machine-written. A file a
	// human might reasonably edit has to say that kbase rewrote it, because
	// kbase will.
	generatedNotice = "<!-- generated by kbase; edits are overwritten on the next build -->"

	// blockRule separates the framing, the conclusions block and the down-link
	// list (§4.2's `---`). It is rendered only around blocks that exist: with
	// no summary artifact for a node, an index is up-link, H1 and its
	// down-links, and that is a valid page rather than a degraded one (O-1).
	blockRule = "---"
)

// Renderer renders the node kinds stage 8 owns — index and entry-point — and
// the class-B fixtures that ship beside them.
//
// Leaves are not here: stage 5 rendered them whole and stage 8 copies them
// byte-for-byte, because rebasing happened once and this stage does not touch
// leaf bytes [MAD1: F-9].
type Renderer struct {
	plan     treeplan.TreePlan
	prov     distill.Provenance
	children map[string][]treeplan.Node
	titles   map[string]string

	// summaries is stage 6's output, keyed by node path — the three string
	// fields §4.2 leaves to a model. A node with no entry renders without a
	// conclusions block, which is the whole tree's state before stage 6 runs
	// and a legal shape after it (O-1).
	summaries map[string]summarize.Summary
}

// NewRenderer returns a renderer over one job's tree plan and whatever
// summaries stage 6 produced for it.
//
// summaries may be nil: that is the no-model build, where every index renders
// with its framing and conclusions absent. It is the SAME code path stage 6
// fills in, not a temporary one — which is what made the mechanical spine
// worth assembling before this stage existed.
func NewRenderer(plan treeplan.TreePlan, prov distill.Provenance, summaries map[string]summarize.Summary) (*Renderer, error) {
	if plan.Schema != treeplan.SchemaVersion {
		return nil, fmt.Errorf("assemble: tree plan declares schema %q, this build reads %q",
			plan.Schema, treeplan.SchemaVersion)
	}
	if err := prov.Validate(); err != nil {
		return nil, err
	}
	r := &Renderer{
		plan:      plan,
		prov:      prov,
		children:  map[string][]treeplan.Node{},
		titles:    make(map[string]string, len(plan.Nodes)),
		summaries: summaries,
	}
	for _, n := range plan.Nodes {
		r.titles[n.Path] = n.Title
		if n.Parent != "" {
			r.children[n.Parent] = append(r.children[n.Parent], n)
		}
	}
	return r, nil
}

// Node renders one index or entry-point node.
func (r *Renderer) Node(n treeplan.Node) ([]byte, error) {
	switch n.Kind {
	case treeplan.KindEntryPoint:
		return r.entryPoint(n)
	case treeplan.KindIndex:
		return r.index(n)
	default:
		return nil, fmt.Errorf("assemble: %s is a %s; stage 8 copies pages, it does not render them", n.Path, n.Kind)
	}
}

// index renders §4.2's grammar.
//
// The framing and conclusions blocks are the model's, and their ABSENCE is
// legal (O-1): with no summary artifact for this node, a mechanically
// renderable index is frontmatter, up-link, H1 and the down-link list.
// Everything else on
// the page comes from the tree plan, which is why a worthless summary costs a
// reader tokens and cannot misroute them (I-4).
func (r *Renderer) index(n treeplan.Node) ([]byte, error) {
	kids := r.children[n.Path]
	if len(kids) == 0 {
		return nil, fmt.Errorf("assemble: %s is a section with no entries under it", n.Path)
	}
	if _, ok := r.titles[n.Parent]; !ok {
		return nil, fmt.Errorf("assemble: %s names parent %q, which the tree plan does not hold", n.Path, n.Parent)
	}
	var b strings.Builder
	b.WriteString(distill.Frontmatter(n.Path))
	b.WriteString("\n\n")
	b.WriteString(distill.UpLink(n.Path, n.Parent))
	b.WriteString("\n\n# ")
	b.WriteString(n.Title)
	b.WriteString("\n\n")
	r.summary(&b, n)
	b.WriteString(derivationsHeading)
	b.WriteString("\n\n")
	r.downLinks(&b, n, kids)
	b.WriteString("\n")
	b.WriteString(r.prov.Footer())
	b.WriteString("\n")
	return []byte(b.String()), nil
}

// summary writes the two model-written blocks of §4.2 — the framing and the
// conclusions — with the rules that separate them, and writes nothing at all
// for a node that has no summary.
//
// The conclusions heading is the MODEL's, deliberately: "Key Results" is not a
// property of knowledge bases, it is a property of a results-dense source
// (§0.5), and an empty conclusions block with a framing above it is a legal
// answer for an index over purely navigational material (§4.5.6).
func (r *Renderer) summary(b *strings.Builder, n treeplan.Node) {
	s, ok := r.summaries[n.Path]
	if !ok || (s.Framing == "" && s.Conclusions == "") {
		return
	}
	if s.Framing != "" {
		b.WriteString(s.Framing)
		b.WriteString("\n\n")
		b.WriteString(blockRule)
		b.WriteString("\n\n")
	}
	if s.Conclusions == "" {
		return
	}
	b.WriteString("## ")
	b.WriteString(s.ConclusionsHeading)
	b.WriteString("\n\n")
	b.WriteString(s.Conclusions)
	b.WriteString("\n\n")
	b.WriteString(blockRule)
	b.WriteString("\n\n")
}

// entryPoint renders §4.3's grammar, including the three blocks [MAD1: F-5]
// made template elements: the contract text, the `.agents/` pointer, and the
// annex lookup when there is one.
func (r *Renderer) entryPoint(n treeplan.Node) ([]byte, error) {
	kids := r.children[n.Path]
	if len(kids) == 0 {
		return nil, fmt.Errorf("assemble: the entry-point has no domains")
	}
	var b strings.Builder
	// The entry-point carries no up-link and still opens with its Location
	// block: the frontmatter is a property of a class-A page, not of having a
	// parent.
	b.WriteString(distill.Frontmatter(n.Path))
	b.WriteString("\n\n# ")
	b.WriteString(n.Title)
	b.WriteString("\n\n")
	// The entry-point's conclusions block is OPTIONAL (O-11): a small,
	// results-dense corpus can carry corpus-wide conclusions under the token
	// ceiling and a large one cannot, so the grammar is the index's with the
	// up-link omitted and the ceiling enforced by refusal at stage 9.
	r.summary(&b, n)
	b.WriteString(domainsHeading)
	b.WriteString("\n\n")
	r.downLinks(&b, n, kids)
	b.WriteString("\n")
	b.WriteString(usingHeading)
	b.WriteString("\n\n")
	b.WriteString(contractText)
	b.WriteString("\n\n")
	b.WriteString(agentsPointer)
	b.WriteString("\n")
	if len(r.plan.Annexes) > 0 {
		b.WriteString("\n")
		b.WriteString(annexHeading)
		b.WriteString("\n\n")
		for _, a := range r.plan.Annexes {
			fmt.Fprintf(&b, "- `%s` — %s\n", a.Prefix, a.Convention)
		}
	}
	b.WriteString("\n")
	b.WriteString(r.prov.Footer())
	b.WriteString("\n")
	return []byte(b.String()), nil
}

// downLinks writes the children list: title and scope straight from the tree
// plan, paths computed (§2.2).
func (r *Renderer) downLinks(b *strings.Builder, parent treeplan.Node, kids []treeplan.Node) {
	for _, c := range kids {
		fmt.Fprintf(b, "- [%s](%s) — %s\n", c.Title, distill.RelPath(parent.Path, c.Path), c.Scope)
	}
}

// Children is one node's children in tree-plan order — the same order the
// down-link list renders in, which is what §9 check 5 compares against.
func (r *Renderer) Children(path string) []treeplan.Node { return r.children[path] }
